version: '3'
services:
    laravel.test:
        build:
            context: _docker_build
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
      #PostgreSQL Service
    pgsql:
        image: 'postgres:12.0-alpine'
        container_name: laravel-pgsql
        working_dir: '/data/pgsql'
        volumes:
             - './postgresql-data:/var/lib/postgresql/data'
        environment:
              POSTGRES_USER: '${DB_USERNAME}'
              POSTGRES_PASSWORD: '${DB_PASSWORD}'
              POSTGRES_DB: '${DB_DATABASE}'
        ports:
             - '5432:5432'
        networks:
             - sail
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
