version: '3'
services:
    laravel.test:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
            - selenium
      #PostgreSQL Service
    pgsql:
        image: 'postgres:12.0-alpine'
        container_name: laravel-pgsql
        working_dir: '/data/pgsql'
        volumes:
             - './postgresql-data:/var/lib/postgresql/data'
        environment:
              POSTGRES_USER: '${DB_USERNAME}'
              POSTGRES_PASSWORD: '${DB_PASSWORD}'
              POSTGRES_DB: '${DB_DATABASE}'
        ports:
             - '5432:5432'
        networks:
             - sail

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    selenium:
       image: 'selenium/standalone-chrome'
       volumes:
            - '/dev/shm:/dev/shm'
       networks:
           - sail
networks:
    sail:
        driver: bridge
volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
